# Generated by Django 5.0 on 2024-02-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
                ('Narxi', models.IntegerField()),
                ('Rasmi', models.ImageField(upload_to='Pivo')),
                ('Tarif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Salat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
                ('Narxi', models.IntegerField()),
                ('Rasmi', models.ImageField(upload_to='Salat')),
                ('Tarif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
                ('Narxi', models.IntegerField()),
                ('Rasmi', models.ImageField(upload_to='taom')),
                ('Tarif', models.TextField()),
            ],
        ),
    ]
